data = {"5": {"Натуральные числа и нуль": "https://youtu.be/6yZ3rYs95fg",
              "Дроби": "https://youtu.be/FmhkBvL4QMQ",
              "Решение текстовых задач": "https://youtu.be/cSXsqO--bgk",
              "Наглядная геометрия": "https://youtu.be/yciwCdP41Zo"},
        "6": {"Натуральные числа": "https://youtu.be/e5eL0ZOmeIM",
              "Дроби": "https://youtu.be/5z1jpfdJYIM",
              "Положительные и отрицательные": "https://youtu.be/hW0vt5qHf4w",
              "Буквенные выражения": "https://youtu.be/r5CRNY7b56I",
              "Решение текстовых задач": "https://youtu.be/PEAwZDCwF6s",
              "Наглядная геометрия": "https://youtu.be/xLr9g_PWb5s"},
        "7": {"Рациональные числа": "https://youtu.be/n-MAagyfxbE",
              "Алгебраические выражения": "https://youtu.be/7vGOZNugnT0",
              "Уравнения": "https://youtu.be/95igra8NEmQ",
              "Координаты и графики. Функции": "https://youtu.be/lcLUzSybvwY"},
        "8": {"Числа и вычисления. Работа": "https://youtu.be/-73fNIIRIYc",
              "Алгебраические выражения": "https://youtu.be/WVwVe_DR3AI",
              "Уравнения и неравенства": "https://youtu.be/cT1_LZMvnvw",
              "Функции": "https://youtu.be/VlU4eyEl1Fo"},
        "9": {"Действительные числа": "https://youtu.be/XmGU87ErBRE",
              "Измерения, приближения, оценки": "https://youtu.be/SOxQkl5FVNo",
              "Уравнения с одной переменной": "https://youtu.be/Ms2slzK2M3M",
              "Системы уравнений": "https://youtu.be/osKZaxtVom4",
              "Системы неравенств": "https://youtu.be/VwNenY6YraY",
              "Функции": "https://youtu.be/Ka06DmnnhWw",
              "Числовые последовательности": "https://youtu.be/aHyVQ9h8moA",
              "Арифметическая и геометрическая": "https://youtu.be/vXOEfy4cKmo"},
        "10": {"Тригонометрические выражения": "https://youtu.be/SjPwsxezly4",
               "Делимость чисел": "https://youtu.be/X78viwekUjM",
               "Многочлены. Алгебраические": "https://youtu.be/IO-ECB0cXjU",
               "Степень с действительным": "https://youtu.be/PbsCRV8RnL4",
               "Степенная функция": "https://youtu.be/VaaQnS3fTRs",
               "Показательная функция": "https://youtu.be/fw9-gSNlzxw",
               "Логарифмическая функция": "https://youtu.be/Ti1aGKAcP-Q",
               "Тригонометрические уравнения": "https://youtu.be/bCkpX0ceO7s"},
        "11": {"Тригонометрические функции": "https://youtu.be/1fL6x_mMpGY",
               "Производная и её геометрический": "https://youtu.be/41N_DxMfJdo",
               "Первообразная и интеграл": "https://youtu.be/EFoRZIn1RRg",
               "Комбинаторика": "https://youtu.be/3KIz8d_IG3I",
               "Элементы теории вероятностей": "https://youtu.be/_dXEMtdD550",
               "Комплексные числа": "https://youtu.be/PSTZzpL11mM",
               "Уравнения и неравенства":"https://youtu.be/rNh_UNVVONU"}
        }